<div id="dv_logoadmin">
    <img src="<?= PUBLIC_PATH?>img/logo.png" alt="Logo Instituto Técnico Surcolombiano">
</div>
<div id="dv_institutoadmin">
    <h1>INSTITUTO TÉCNICO SURCOLOMBIANO</h1>
</div>
<? if($view > 0 && Auth::is_valid()): ?>
    <div style="width: 100%; height: 60px; background-color: #ffffff">
        <span onclick="window.location = '<?= PUBLIC_PATH?>management/matricula'">Matricula</span>
        <button onclick="window.location = '<?= PUBLIC_PATH?>account/salirAdmin'">Salir</button>
    </div>
<? endif; ?>