<div id="dv_resultadosegresados">
    <? foreach($egresados->items as $egresado): ?>
        <div class="contenedor_resultadoegresado">
            <a class="enlace_datosegresado" href="<?= PUBLIC_PATH?>management/egresado/<?= $egresado->identificacion_alumno?>" target="_blank">(<?= $egresado->identificacion_alumno?>) <?= $egresado->nombre_alumno . ' ' . $egresado->apellido_alumno?></a>
            <!--span class="etiqueta_datosegresado">(<?= $egresado->id_alumno?>) <?= $egresado->valor_nota?></span-->
        </div>
    <? endforeach; ?>
</div>
<? if($egresados->total > 1): ?>
    <div id="dv_paginacion">
        <? View::partial('paginators/classic', false, array('page' => $egresados, 'show' => 5, 'programa' => $programa, 'anio' => $anio)); ?>
    </div>
<? endif; ?>