<div class="contenedor_formularioadmin contenedor_formulariomatricula">
    <span class="etiqueta_encabezadoformlarioadmin">CONSULTAR ACTA</span>
    <div id="dv_documentoacta">
        <div>
            <span>Número de Documento</span>
            <input id="txt_numerodocumentoconsultar" class="entrada_datoformularioadmin" type="text" autofocus required="required" onkeypress="return soloNumeros(event);">
        </div>
        <div>
            <input id="btn_consultardocumento" class="boton_buscardocumento" type="button" value="Buscar">
        </div>
    </div>
    <div id="dv_formularioacta" class="displaynone"></div>
</div>
<div class="contendor_regresarprincipal">
    <a href="<?= PUBLIC_PATH?>management/actas" class="etiqueta_regresarprincipal">Regresar</a>
</div>
<div id="dv_dialogodocumnetoinexistente">
    <? Flash::info('El número de documento no se encuentra registrado en nuestra base de datos de egresados. Click en "Aceptar" para regresar') ?>
</div>

<script type="text/javascript">
    $('#dv_dialogodocumnetoinexistente').dialog({
        autoOpen: false,
        modal: true,
        resizable: false,
        closeOnEscape: false,
        buttons: {
            "Aceptar": function() {
                $('#dv_dialogodocumnetoinexistente').dialog('close');
            }
        },
        close: function (){}
    });
    
    function cargarFormActa(documento){
        $.ajax({
            type: 'POST',
            url: <?= PUBLIC_PATH?> + 'management/formularioacta/',
            data: {
                tipo: 2,
                documento: documento
            },
            beforeSend: function(){
                $('body').addClass('menuopen');
                
                $.blockUI({
                    message: "Cargando formulario de matricula..."
                });
            },
            success: function(data) {
                $('body').removeClass('menuopen');
                
                $('#dv_formularioacta').html('');
                $('#dv_formularioacta').html(data);
                $('#dv_formularioacta').removeClass('displaynone');
                
                rs();
            },
            error: function(){
                
            }
        }).always(function(){
            $.unblockUI();
        });
    }
    
    $('#btn_consultardocumento').on('click', function (){
        var documento = $('#txt_numerodocumentoconsultar').val();
        
        if(documento.length > 0){
            $.ajax({
                type: 'POST',
                url: <?= PUBLIC_PATH?> + 'management/consultarDatosActaAlumno/',
                data: {
                    documento: documento
                },
                dataType: 'json',
                beforeSend: function(){
                    //document.getElementById("btn_consultarnotas").disabled = true;
                    
                    $('body').addClass('menuopen');
                    
                    $.blockUI({
                        message: "Validando datos..."
                    });
                },
                success: function(data) {
                    $('body').removeClass('menuopen');
                   
                    if(data !== null && data.res === 'ok'){
                        $('#dv_documentoacta').addClass('displaynone');
                        $('#txt_numerodocumentoconsultar').val('');
                        
                        cargarFormActa(documento);
                    }else{
                        $('#txt_numerodocumentoconsultar').val('').focus();
                        $('#dv_dialogodocumnetoinexistente').dialog('open');
                        
                        console.log(data.msg);
                    }
                },
                error: function(){
                    console.log('Ocurrio un error inesperado. Intenta nuevamente');
                }
            }).always(function(){
                $.unblockUI();
            });
        }else{
            $inputfocus = null;
            $input = $('#txt_numerodocumentoconsultar');
            if(documento.length === 0){
                $input.addClass('entrada_textonovalido');
                if($inputfocus === null)$inputfocus = $input;
            }else{
                $input.removeClass('entrada_textonovalido');
            }
            
            if($inputfocus !== null){
                $('html, body').animate({scrollTop: $inputfocus.position().top+'px'}, 1000);
                $inputfocus.focus();
            }
        }
    });
    
    $('#txt_numerodocumentoconsultar').keypress(function(e) {
        if(e.which == 13) {
            $(this).blur();
            $('#btn_consultardocumento').click();
        }
    });
    
    $('#txt_numerodocumentoconsultar').on('keyup', function() {
        var txt = $(this).val();
        
        if (txt.length <= 0) {
            $(this).addClass('entrada_textonovalido');
        } else {
            $(this).removeClass('entrada_textonovalido');
        }
    });
</script>