<div id="dv_resultadoseguimientoegresados">
    <span id="sp_tituloresultadoseguimientoegresados">Egresado, <?= $datosegresado[0]->nombre_egresado . ' ' . $datosegresado[0]->apellido_egresado?></span>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_datoegresado">Número de Documento</label>
            <input class="texto_datoegresado" type="text" value="<?= $datosegresado[0]->identificacion_egresado?>" readonly="readonly" disabled="disabled">
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_datoegresado">Programa de Egreso</label>
            <input class="texto_datoegresado" type="text" value="<?= $datosegresado[0]->nombre_programa?>" readonly="readonly" disabled="disabled">
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_datoegresado">Correo Electrónico Egresado</label>
            <input id="txt_correoelectronicoegresado" class="texto_datoegresado" type="text" value="<?= $datosegresado[0]->correo_electronico_egresado?>">
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_datoegresado">Teléfono/Celular Egresado</label>
            <input id="txt_telefonoegresado" class="texto_datoegresado" type="text" value="<?= $datosegresado[0]->telefono_egresado?>" onkeypress="return soloNumeros(event);">
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_datoegresado">Dirección Egresado</label>
            <input id="txt_direccionegresado" class="texto_datoegresado" type="text" value="<?= $datosegresado[0]->direccion_egresado?>">
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_secciondatosegresado">Datos Laborales</label>
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_datoegresado">Empresa Egresado</label>
            <input id="txt_empresaegresado" class="texto_datoegresado" type="text" value="<?= $datosegresado[0]->empresa_egresado?>">
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_datoegresado">Ocupación/Cargo Egresado</label>
            <input id="txt_ocupacionegresado" class="texto_datoegresado" type="text" value="<?= $datosegresado[0]->ocupacion_egresado?>">
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_datoegresado">Dirección Empresa Egresado</label>
            <input id="txt_direccionempresaegresado" class="texto_datoegresado" type="text" value="<?= $datosegresado[0]->direccion_empresa_egresado?>">
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_datoegresado">Teléfono Empresa Egresado</label>
            <input id="txt_telefonoempresaegresado" class="texto_datoegresado" type="text" value="<?= $datosegresado[0]->telefono_empresa_egresado?>" onkeypress="return soloNumeros(event);">
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <input id="btn_actualizardatosegresado" class="boton_actualizardatosegresado" type="button" value="Actualizar Datos">
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_secciondatosegresado">Seguimiento a Egresado</label>
        </div>
    </div>
    <? if(!empty($seguimiento)): ?>
        <div id="dv_opcionesresultadoseguimientoegresados">
            <div>
                <label class="etiqueta_datoegresado">Fecha Último Seguimiento</label>
                <input class="texto_datoegresado" type="text" value="<?
                    $time = strtotime($seguimiento[0]->fecha_seguimientoegresado);
                    $format = date('Y-m-d', $time);
                    
                    echo $format;
                ?>" readonly="readonly" disabled="disabled">
            </div>
        </div>
    <? endif; ?>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_datoegresado">Observación/Descripción</label>
            <textarea id="txt_observacionseguimiento" class="texto_datoegresado texto_seguimientoegresado" rows="5"></textarea>
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <label class="etiqueta_datoegresado etiqueta_llamadaseguimientoegresado">LLamada</label>
            <input class="caja_llamadaseguimientoegresado" type="checkbox" name="llamada" value="1">
        </div>
    </div>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <input id="btn_seguimientoegresado" class="boton_seguimientoegresado" type="button" value="Registrar Seguimiento">
        </div>
    </div>
</div>
<div id="dv_dialogoconfirmacionactualizacionegresado">
    <span>Actulización de datos extosa. Aceptar para continuar con el seguimiento a egresado o salir del sistema administrativo</span>
</div>
<div id="dv_dialogoconfirmacionregistroseguimiento">
    <span>Seguimiento a egresado registrado extosamente. Aceptar para continuar con el seguimiento a egresados o salir del sistema administrativo</span>
</div>

<script type="text/javascript">
    $('#dv_dialogoconfirmacionactualizacionegresado').dialog({
        autoOpen: false,
        modal: true,
        resizable: false,
        closeOnEscape: false,
        buttons: {
            "Aceptar": function() {
                location.reload();
            }
        },
        close: function (){}
    });
    
    $('#dv_dialogoconfirmacionregistroseguimiento').dialog({
        autoOpen: false,
        modal: true,
        resizable: false,
        closeOnEscape: false,
        buttons: {
            "Aceptar": function() {
                window.close();
            }
        },
        close: function (){}
    });
    
    $('#btn_actualizardatosegresado').on('click', function (){
        var correo = $('#txt_correoelectronicoegresado').val(),
            telefono = $('#txt_telefonoegresado').val(),
            direccion = $('#txt_direccionegresado').val(),
            empresa = $('#txt_empresaegresado').val(),
            ocupacion = $('#txt_ocupacionegresado').val(),
            dirempresa = $('#txt_direccionempresaegresado').val(),
            telempresa = $('#txt_telefonoempresaegresado').val();
        
        if(correo.length > 0 && validar_email(correo) && telefono.length > 0 && direccion.length > 0 && empresa.length > 0 && ocupacion.length > 0 && dirempresa.length > 0 && telempresa.length > 0){
            $.ajax({
                type: 'POST',
                url: <?= PUBLIC_PATH?> + 'management/actulizardatosegresado/',
                data: {
                    egresado: <?= $datosegresado[0]->id_egresado?>,
                    correo: correo,
                    telefono: telefono,
                    direccion: direccion,
                    empresa: empresa,
                    ocupacion: ocupacion,
                    dirempresa: dirempresa,
                    telempresa: telempresa
                },
                dataType: 'json',
                beforeSend: function(){
                    $('body').addClass('menuopen');
                    
                    $.blockUI({
                        message: "Registrando acta..."
                    });
                },
                success: function(data) {
                    $('body').removeClass('menuopen');
                    
                    if(data !== null && data.res === 'ok'){
                        $('#dv_dialogoconfirmacionactualizacionegresado').dialog('open');
                        
                        console.log(data.res);
                    }else{
                        console.log(data.msg);
                    }
                },
                error: function(){
                    
                }
            }).always(function(){
                $.unblockUI();
            });
        }else{
            $inputfocus = null;
            $input = $('#txt_correoelectronicoegresado');
            if(correo.length === 0 || !validar_email(correo)){
                $input.addClass('entrada_textonovalido');
                if($inputfocus === null)$inputfocus = $input;
            }else{
                $input.removeClass('entrada_textonovalido');
            }
            $input = $('#txt_telefonoegresado');
            if(telefono.length === 0){
                $input.addClass('entrada_textonovalido');
                if($inputfocus === null)$inputfocus = $input;
            }else{
                $input.removeClass('entrada_textonovalido');
            }
            $input = $('#txt_direccionegresado');
            if(direccion.length === 0){
                $input.addClass('entrada_textonovalido');
                if($inputfocus === null)$inputfocus = $input;
            }else{
                $input.removeClass('entrada_textonovalido');
            }
            $input = $('#txt_empresaegresado');
            if(empresa.length === 0){
                $input.addClass('entrada_textonovalido');
                if($inputfocus === null)$inputfocus = $input;
            }else{
                $input.removeClass('entrada_textonovalido');
            }
            $input = $('#txt_ocupacionegresado');
            if(ocupacion.length === 0){
                $input.addClass('entrada_textonovalido');
                if($inputfocus === null)$inputfocus = $input;
            }else{
                $input.removeClass('entrada_textonovalido');
            }
            $input = $('#txt_direccionempresaegresado');
            if(dirempresa.length === 0){
                $input.addClass('entrada_textonovalido');
                if($inputfocus === null)$inputfocus = $input;
            }else{
                $input.removeClass('entrada_textonovalido');
            }
            $input = $('#txt_telefonoempresaegresado');
            if(telempresa.length === 0){
                $input.addClass('entrada_textonovalido');
                if($inputfocus === null)$inputfocus = $input;
            }else{
                $input.removeClass('entrada_textonovalido');
            }
            
            if($inputfocus !== null){
                $('html, body').animate({scrollTop: $inputfocus.position().top+'px'}, 1000);
                $inputfocus.focus();
            }
        }
    });
    
    $('#btn_seguimientoegresado').on('click', function (){
        var observacion = $('#txt_observacionseguimiento').val(),
            llamada = $('input:checkbox[name=llamada]:checked').val();
        
        $.ajax({
            type: 'POST',
            url: <?= PUBLIC_PATH?> + 'management/registrarseguimientoegresado/',
            data: {
                egresado: <?= $datosegresado[0]->id_egresado?>,
                observacion: observacion,
                llamada: llamada
            },
            dataType: 'json',
            beforeSend: function(){
                $('body').addClass('menuopen');
                
                $.blockUI({
                    message: "Registrando acta..."
                });
            },
            success: function(data) {
                $('body').removeClass('menuopen');
                
                if(data !== null && data.res === 'ok'){
                    $('#dv_dialogoconfirmacionregistroseguimiento').dialog('open');
                    
                    console.log(data.res);
                }else{
                    console.log(data.msg);
                }
            },
            error: function(){
                
            }
        }).always(function(){
            $.unblockUI();
        });
    });
    
    $("#txt_correoelectronicoegresado, #txt_telefonoegresado, #txt_direccionegresado, #txt_empresaegresado, #txt_ocupacionegresado, #txt_direccionempresaegresado, #txt_telefonoempresaegresado").on('keyup', function (){
        if($(this).val().length > 0){
            $(this).removeClass('entrada_textonovalido');
        }else{
            $(this).addClass('entrada_textonovalido');
        }
    });
</script>