<div id="dv_verificarregistraregresados" class="contenedor_opcionegresados">Verificar y Registrar Egresados</div>
<a id="dv_seguimientoegresados" class="contenedor_opcionegresados" href="<?= PUBLIC_PATH?>management/seguimientoegresados/">Seguimiento a Egresados</a>

<script type="text/javascript">
    $('#dv_verificarregistraregresados').on('click', function (){
        $.ajax({
            type: 'POST',
            url: <?= PUBLIC_PATH?> + 'management/registroegresados/',
            data: {},
            beforeSend: function(){
                
            },
            success: function(data) {
                $('#sec_contenidologinadmin').html('');
                $('#sec_contenidologinadmin').html(data);
            },
            error: function(){
                
            }
        }).always(function(){
            
        });
    });
</script>