<form id="frm_matriculaestudiante" class="formulario_admin">
    <?if($bandera==1):?><span class="etiqueta_encabezadoelementoformularioadmin">MATRICULA SEMESTRE NÚMERO:&nbsp;<input class="texto_semestre" type="text" name="semestre" value="<?= ($datos[0]->id_semestre + 1)?>" readonly="readonly"></span><?endif;
    if($bandera == 2): ?>
        <div id="dv_semestrematriculavalidacion">
            <div>
                <input type="radio" name="matricula" value="1" checked>
                <span class="etiqueta_textoradioformularioadmin">Primer Semestre</span>
                <input type="radio" name="matricula" value="2">
                <span class="etiqueta_textoradioformularioadmin">Segundo Semetre</span>
                <input type="radio" name="matricula" value="3">
                <span class="etiqueta_textoradioformularioadmin">Tercer Semetre</span>
            </div>
        </div>
    <? endif; ?>
    <span class="etiqueta_encabezadoelementoformularioadmin">Sede Instituto Técnico Surcolombiano</span>
    <div class="contendor_elementoformularioadmin">
        <div>
            <input type="radio" name="sedematricula" value="1" <?= ($bandera==1&&$datos[0]->id_sede==1)?'cheked':($bandera==0||$bandera==2)?'checked':'';?>>
            <span class="etiqueta_textoradioformularioadmin">Pasto</span>
            <input type="radio" name="sedematricula" value="2" <?= ($bandera==1&&$datos[0]->id_sede==2)?'cheked':'';?>>
            <span class="etiqueta_textoradioformularioadmin">Ipiales</span>
        </div>
    </div>
    <span class="etiqueta_encabezadoelementoformularioadmin">Datos Personales</span>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin etiqueta_espacioelementoformularioadmin">Tipo de Documento</span>
            <?foreach($tipodocumentos as $tipodocumento):?>
                <input type="radio" name="tipodocumento" value="<?= $tipodocumento->id_tipodocumento?>" <?= (($bandera==0||$bandera==2)&&$tipodocumento===end($tipodocumentos))?'checked':($bandera==1&&$datos[0]->id_tipodocumento==$tipodocumento->id_tipodocumento)?'checked':'';?>><?/*= ($bandera==1)?'onclick="return false;"':''*/?>
                <span class="etiqueta_textoradioformularioadmin"><?= $tipodocumento->abreviatura_tipodocumento?></span>
            <?endforeach;?>
            <!--select id="slt_tipodocumento" class="entrada_datoformularioadmin">
                <option value="0">Seleccionar tipo de documento</option>
                <?foreach($tipodocumentos as $tipodocumento):?>
                    <option value="<?= $tipodocumento->id_tipodocumento?>"><?= $tipodocumento->nombre_tipodocumento?></option>
                <?endforeach;?>
            </select-->
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Número de Documento</span>
            <input id="txt_numerodocumento" class="entrada_datoformularioadmin" type="text" name="numerodocumento" required="required" onkeypress="return soloNumeros(event);" <?= ($bandera==1)?'value="'.$datos[0]->identificacion_alumno.'" readonly':'';?>>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin contenedor_elementociudadformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Lugar de Expedición</span>
            <select id="slt_paisE" class="combo_paises entrada_datoformularioadmin entrada_datocomboformularioadmin" name="paisE" <?= ($bandera==1)?'disabled':'';?>>
                <?foreach($paises as $pais):?>
                    <option value="<?= $pais->id_pais?>" <?= (($bandera==0||$bandera==2)&&$pais->id_pais==='82')?'selected':($bandera==1&&$datoslocalidad[0]->id_pais==$pais->id_pais)?'selected':'';?>><?= $pais->nombre_pais?></option>
                <?endforeach;?>
            </select>
            <select id="slt_regionE" class="combo_regiones entrada_datoformularioadmin entrada_datocomboformularioadmin" name="regionE" <?= ($bandera==1)?'disabled':'';?>>
                <option value="0">Región</option>
                <?foreach($regiones as $region):?>
                    <option value="<?= $region->id_region?>" <?= ($bandera==1&&$datoslocalidad[0]->id_region==$region->id_region)?'selected':'';?>><?= $region->nombre_region?></option>
                <?endforeach;?>
            </select>
            <select id="slt_localidadE" class="combo_localidades entrada_datoformularioadmin entrada_datocomboformularioadmin" name="localidadE" <?= ($bandera==1)?'disabled':'';?>>
                <? if($bandera==0||$bandera==2): ?>
                    <option value="0">Localidad</option>
                <? else: ?>
                    <?foreach($localidadesE as $localidadE):?>
                        <option value="<?= $localidadE->id_localidad?>" <?= ($bandera==1&&$datos[0]->lugar_expedicion_identificacion_alumno==$localidadE->id_localidad)?'selected':'';?>><?= $localidadE->nombre_localidad?></option>
                    <?endforeach;?>
                <? endif; ?>
            </select>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Nombre(s)</span>
            <input id="txt_nombre" class="entrada_datoformularioadmin" type="text" name="nombre" required="required" <?= ($bandera==1)?'value="'.$datos[0]->nombre_alumno.'" readonly':'';?>>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Apellido(s)</span>
            <input id="txt_apellido" class="entrada_datoformularioadmin" type="text" name="apellido" required="required" <?= ($bandera==1)?'value="'.$datos[0]->apellido_alumno.'" readonly':'';?>>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Fecha de Nacimiento</span>
            <input id="txt_fechanacimiento" class="entrada_datoformularioadmin" type="text" name="fechanacimiento" placeholder="YYYY-MM-DD" required="required" <?= ($bandera==1)?'value="'.$fechanacimiento.'" readonly':'';?>>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin contenedor_elementociudadformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Lugar de Nacimiento</span>
            <select id="slt_paisN" class="combo_paises entrada_datoformularioadmin entrada_datocomboformularioadmin" name="paisN" <?= ($bandera==1)?'disabled':'';?>>
                <?foreach($paises as $pais):?>
                    <option value="<?= $pais->id_pais?>" <?= (($bandera==0||$bandera==2)&&$pais->id_pais==='82')?'selected':($bandera==1&&$datoslocalidad[0]->id_pais==$pais->id_pais)?'selected':'';?>><?= $pais->nombre_pais?></option>
                <?endforeach;?>
            </select>
            <select id="slt_regionN" class="combo_regiones entrada_datoformularioadmin entrada_datocomboformularioadmin" name="regionN" <?= ($bandera==1)?'disabled':'';?>>
                <option value="0">Región</option>
                <?foreach($regiones as $region):?>
                    <option value="<?= $region->id_region?>" <?= ($bandera==1&&$datoslocalidad[0]->id_region==$region->id_region)?'selected':'';?>><?= $region->nombre_region?></option>
                <?endforeach;?>
            </select>
            <select id="slt_localidadN" class="combo_localidades entrada_datoformularioadmin entrada_datocomboformularioadmin" name="localidadN" <?= ($bandera==1)?'disabled':'';?>>
                <? if($bandera==0||$bandera==2): ?>
                    <option value="0">Localidad</option>
                <? else: ?>
                    <?foreach($localidades as $localidad):?>
                        <option value="<?= $localidad->id_localidad?>" <?= ($bandera==1&&$datos[0]->lugar_nacimiento_alumno==$localidad->id_localidad)?'selected':'';?>><?= $localidad->nombre_localidad?></option>
                    <?endforeach;?>
                <? endif; ?>
            </select>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Dirección</span>
            <input id="txt_direccion" class="entrada_datoformularioadmin" type="text" name="direccion" required="required" <?= ($bandera==1)?'value="'.$datos[0]->direccion_alumno.'"':'';?>>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Teléfono/Celular</span>
            <input id="txt_telefono" class="entrada_datoformularioadmin" type="text" name="telefono" required="required" onkeypress="return soloNumeros(event);" <?= ($bandera==1)?'value="'.$datos[0]->telefono_alumno.'"':'';?>>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Correo Electrónico</span>
            <input id="txt_correoelectronico" class="entrada_datoformularioadmin" type="email" name="correoelectronico" required="required" <?= ($bandera==1)?'value="'.$datos[0]->correo_electronico_alumno.'"':'';?>>
        </div>
    </div>
    <span class="etiqueta_encabezadoelementoformularioadmin">Datos Acudiente</span>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Nombre(s)</span>
            <input id="txt_nombreA" class="entrada_datoformularioadmin" type="text" name="nombreA" required="required" <?= ($bandera==1)?'value="'.$datos[0]->nombre_acudiente_alumno.'"':'';?>>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Apellido(s)</span>
            <input id="txt_apellidoA" class="entrada_datoformularioadmin" type="text" name="apellidoA" required="required" <?= ($bandera==1)?'value="'.$datos[0]->apellido_acudiente_alumno.'"':'';?>>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Teléfono/Celular</span>
            <input id="txt_telefonoA" class="entrada_datoformularioadmin" type="text" name="telefonoA" required="required" onkeypress="return soloNumeros(event);" <?= ($bandera==1)?'value="'.$datos[0]->telefono_acudiente_alumno.'"':'';?>>
        </div>
    </div>
    <span class="etiqueta_encabezadoelementoformularioadmin">Datos Laborales</span>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Empresa</span>
            <input id="txt_empresa" class="entrada_datoformularioadmin" type="text" name="empresa" required="required" <?= ($bandera==1)?'value="'.$datos[0]->empresa_alumno.'"':'';?>>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Ocupación/Cargo</span>
            <input id="txt_cargo" class="entrada_datoformularioadmin" type="text" name="cargo" required="required" <?= ($bandera==1)?'value="'.$datos[0]->ocupacion_alumno.'"':'';?>>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Dirección</span>
            <input id="txt_direccionE" class="entrada_datoformularioadmin" type="text" name="direccionE" required="required" <?= ($bandera==1)?'value="'.$datos[0]->direccion_empresa_alumno.'"':'';?>>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Teléfono/Celular</span>
            <input id="txt_telefonoE" class="entrada_datoformularioadmin" type="text" name="telefonoE" required="required" onkeypress="return soloNumeros(event);" <?= ($bandera==1)?'value="'.$datos[0]->telefono_empresa_alumno.'"':'';?>>
        </div>
    </div>
    <span class="etiqueta_encabezadoelementoformularioadmin">Datos Programa</span>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Programa</span>
            <select id="slt_programa" class="entrada_datoformularioadmin" name="programa" <?= ($bandera==1)?'disabled':'';?>>
                <option value="0">Seleccionar programa</option>
                <?foreach($programas as $programa):?>
                    <option data-valor="<?= $programa->valor_semestre_programa?>" value="<?= $programa->id_programa?>" <?= ($bandera==1&&$datos[0]->id_programa==$programa->id_programa)?'selected':'';?>><?= $programa->nombre_programa?></option>
                <?endforeach;?>
            </select>
        </div>
    </div>
    <!--div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Semestre</span>
            <select id="slt_tipodocumento" class="entrada_datoformularioadmin">
                <option value="0">Seleccionar semestre</option>
                <?foreach($semestres as $semestre):?>
                    <option value="<?= $semestre->id_semestre?>"><?= $semestre->nombre_semestre?></option>
                <?endforeach;?>
            </select>
        </div>
    </div-->
    <span class="etiqueta_encabezadoelementoformularioadmin">Datos Matrícula</span>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin etiqueta_anchoelementoformularioadmin">Periodo (<?= date("Y");?>)</span>
            <input type="radio" name="periodomatricula" value="1" <?= ($bandera==1&&$datos[0]->id_periodo==1)?'checked':($bandera==0||$bandera==2)?'checked':'';?>>
            <span class="etiqueta_textoradioformularioadmin">A</span>
            <input type="radio" name="periodomatricula" value="2" <?= ($bandera==1&&$datos[0]->id_periodo==2)?'checked':'';?>>
            <span class="etiqueta_textoradioformularioadmin">B</span>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Código Estudiante</span>
            <input id="txt_codigoestudiantil" class="entrada_datoformularioadmin" type="text" name="codigoestudiantil" readonly="readonly" required="required" <?= ($bandera==1)?'value="'.$datos[0]->identificacion_alumno.'"':'';?>>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Número Matrícula</span>
            <input id="txt_numeromatricula" class="entrada_datoformularioadmin" type="text" name="numeromatricula" value="<?= $numeromatricula?>" readonly="readonly" required="required">
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin">Fecha Matricula</span>
            <input id="txt_fechamatricula" class="entrada_datoformularioadmin" type="text" name="fechamatricula" value="<?= date('Y-m-d')?>" readonly="readonly" required="required">
        </div>
    </div>
    <span class="etiqueta_encabezadoelementoformularioadmin">Datos Pago</span>
    <div class="contendor_elementoformularioadmin">
        <div>
            <span class="etiqueta_textoelementoformularioadmin etiqueta_bacaelementoformularioadmin">¿Beca?</span>
            <input id="rb_becatrue" type="radio" name="beca" value="1">
            <span class="etiqueta_textoradioformularioadmin">Si</span>
            <input id="rb_becafalse" type="radio" name="beca" value="2" checked="checked">
            <span class="etiqueta_textoradioformularioadmin">No</span>
        </div>
    </div>
    <div id="dv_datospagomatricula" class="contendor_elementoformularioadmin">
        <div class="contendor_elementoformularioadmin">
            <div>
                <span class="etiqueta_textoelementoformularioadmin etiqueta_valormatricula">Valor Matrícula (Semestre)</span>
                <input id="txt_valormatricula" class="entrada_datoformularioadmin entrada_valormatricula" type="number" name="valormatricula" min="0" step="50000" value="<?= ($bandera==1)?$datos[0]->valor_matricula:'0';?>" required="required">
            </div>
        </div>
        <div class="contendor_elementoformularioadmin">
            <div>
                <span class="etiqueta_textoelementoformularioadmin etiqueta_espacioelementoformularioadmin">Forma de Pago</span>
                <?foreach($formapagos as $formapago):?>
                    <input id="rb_fp<?= $formapago->nombre_formapago?>" type="radio" name="formapago" value="<?= $formapago->id_formapago?>" <?= ($formapago===reset($formapagos))?'checked':'';?>>
                    <span class="etiqueta_textoradioformularioadmin"><?= $formapago->nombre_formapago?></span>
                <?endforeach;?>
            </div>
        </div>
        <div id="dv_numerocuotas" class="contendor_elementoformularioadmin displaynone">
            <div>
                <span class="etiqueta_textoelementoformularioadmin">Número de Cuotas</span>
                <input id="num_numerocuotas" class="entrada_datoformularioadmin" type="number" name="numerocuotas" value="1" min="2" required="required">
            </div>
        </div>
    </div>
    <div class="contendor_elementoformularioadmin">
        <input id="btn_registrarestudiante" class="boton_formularioadmin" type="button" value="Registrar">
    </div>
</form>

<script type="text/javascript">
    <? if($bandera == 0 || $bandera == 2): ?>
        $('#txt_fechanacimiento').datepicker({
            changeMonth: true,
            changeYear: true,
            //yearRange: "1950:+nn",
            yearRange: "1950:" + new Date().getFullYear(),

            onSelect: function (selectedDateTime){
                $(this).removeClass('entrada_textonovalido');
            }
        });
    <? endif; ?>
    
    /*$('#txt_fechanacimiento').datetimepicker({
	controlType: 'select',
	oneLine: true,
	dateFormat: 'yy-mm-dd',
	timeFormat: 'HH:mm:ss',
        minDate: new Date(),
        
        onSelect: function (selectedDateTime){
            $(this).removeClass('cajastexto_novalida');
        }
    });*/
    
    $('#rb_fpContado').on('click', function (){
        $('#dv_numerocuotas').addClass('displaynone');
        $('#num_numerocuotas').val(1);
    });
    
    $('#rb_fpCuotas').on('click', function (){
        $('#dv_numerocuotas').removeClass('displaynone');
        $('#num_numerocuotas').val(2);
    });
    
    $('#rb_becatrue').on('click', function (){
        $('#dv_datospagomatricula').addClass('displaynone');
        $('#txt_valormatricula').val('0');
        document.getElementById('rb_fpContado').checked = true;
        $('#dv_numerocuotas').addClass('displaynone');
        $('#num_numerocuotas').val(1);
    });
    
    $('#rb_becafalse').on('click', function (){
        $('#dv_datospagomatricula').removeClass('displaynone');
        $('#txt_valormatricula').val('0');
        document.getElementById('rb_fpContado').checked = true;
        $('#dv_numerocuotas').addClass('displaynone');
        $('#num_numerocuotas').val(1);
    });
    
    $('.combo_paises').change(function(){
        var p = $(this);
        
        if($(this).val().length > 0){
            var pais = $(this).val();
            
            $.ajax({
                type: 'GET',
                url: "<?= PUBLIC_PATH . 'management/obtenerRegiones/'?>" + pais,
                dataType: 'json',
                success: function(data){
                    try{
                        var bandera = 0;
                        
                        p.next().empty();
                        p.next().append('<option value="0">Región</option>');
                        p.next().next().empty();
                        p.next().next().append('<option value="0">Localidad</option>');
                        
                        for(var i=0; i<data.length; i++){
                            try {
                                p.next().append('<option value="' + data[i].id_region + '">'+ data[i].nombre_region + '</option>');
                            }catch(e){
                                bandera = 1;
                            }
                        }
                    }catch(e){
                        
                    }
                },
                error: function (xhr, ajaxOptions, thrownError){ } 
            });
        }
    });
    
    $('.combo_regiones').change(function(){
        var r = $(this);
        
        if($(this).val().length > 0){
            var pais = $(this).prev().val(),
                region = $(this).val();
            
            $.ajax({
                type: 'GET',
                url: "<?= PUBLIC_PATH . 'management/obtenerLocalidades/'?>" + pais + "/" + region,
                dataType: 'json',
                success: function(data){
                    try{
                        var bandera = 0;
                        
                        r.next().empty();
                        r.next().append('<option value="0">Localidad</option>');
                        
                        for(var i=0; i<data.length; i++){
                            try {
                                r.next().append('<option value="' + data[i].id_localidad + '">'+ data[i].nombre_localidad + '</option>');
                            }catch(e){
                                bandera = 1;
                            }
                        }
                    }catch(e){
                        
                    }
                },
                error: function (xhr, ajaxOptions, thrownError){ } 
            });
        }
    });
    
    $('#txt_numerodocumento').on('keyup', function (){
        var documento = $(this).val();    
        var codigo = $('#txt_codigoestudiantil');
        
        codigo.val(documento);
    });
    
    $('#btn_registrarestudiante').on('click', function (){
        var matricula = convertiranumero(document.querySelector('input[name="matricula"]:checked').value),
            //sede = convertiranumero(document.querySelector('input[name="sedematricula"]:checked').value),
            //tipoDocumento = convertiranumero(document.querySelector('input[name="tipodocumento"]:checked').value),
            documento = $('#txt_numerodocumento').val(),
            //pais = $('#slt_paisE option:selected').val(),
            region = $('#slt_regionE option:selected').val(),
            localidad = $('#slt_localidadE option:selected').val(),
            nombre = $('#txt_nombre').val(),
            apellido = $('#txt_apellido').val(),
            fechaNacimiento = $('#txt_fechanacimiento').val(),
            //paisNacimiento = $('#slt_paisN option:selected').val(),
            regionNacimiento = $('#slt_regionN option:selected').val(),
            localidadNacimiento = $('#slt_localidadN option:selected').val(),
            direccion = $('#txt_direccion').val(),
            telefono = $('#txt_telefono').val(),
            correoElectronico = $('#txt_correoelectronico').val(),
            //nombreAcudiente = $('#txt_nombreA').val(),
            //apellidoAcudiente = $('#txt_apellidoA').val(),
            //telefonoAcudiente = $('#txt_telefonoA').val(),
            //empresa = $('#txt_empresa').val(),
            //cargo = $('#txt_cargo').val(),
            //direccionEmpresa = $('#txt_direccionE').val(),
            //telefonoEmpresa = $('#txt_telefonoE').val(),
            programa = $('#slt_programa option:selected').val(),
            //periodo = convertiranumero(document.querySelector('input[name="periodomatricula"]:checked').value),
            codigoEstudiante = $('#txt_codigoestudiantil').val(),
            numeroMatricula = $('#txt_numeromatricula').val(),
            fechaMatricula = $('#txt_fechamatricula').val(),
            valorMatricula = $('#txt_valormatricula').val();
            //formaPago = convertiranumero(document.querySelector('input[name="formapago"]:checked').value),
            //numeroCuotas = $('#num_numerocuotas').val();
        
        if(documento.length > 0 && convertiranumero(region) > 0 && convertiranumero(localidad) > 0
            && nombre.length > 0 && apellido.length > 0 && fechaNacimiento.length > 0
            && convertiranumero(regionNacimiento) > 0 && convertiranumero(localidadNacimiento) > 0 && direccion.length > 0
            && telefono.length > 0 && correoElectronico.length > 0 && validar_email(correoElectronico)
            && convertiranumero(programa) > 0 && codigoEstudiante.length > 0
            && numeroMatricula.length > 0 && fechaMatricula.length > 0 && valorMatricula.length > 0){
            
            <? if($bandera==2): ?>
                $.ajax({
                    type: 'POST',
                    url: <?= PUBLIC_PATH?> + 'management/registrarEstudiante/',
                    data: $('#frm_matriculaestudiante').serialize(),
                    dataType: 'json',
                    beforeSend: function(){
                        //document.getElementById("btn_consultarnotas").disabled = true;

                        $('body').addClass('menuopen');

                        $.blockUI({
                            message: "Registrando y matriculando estudiante..."
                        });
                    },
                    success: function(data) {
                        $('body').removeClass('menuopen');
                        //document.getElementById("frm_codigoestudiante").reset();

                        if(data !== null && data.res === 'ok'){
                            window.localStorage.idPagoMatricula = data.id;

                            document.location = <?= PUBLIC_PATH?> + 'management/pagomatricula/' + data.id;

                            console.log(data.res);
                        }else{
                            console.log(data.msg);
                        }
                    },
                    error: function(){
                        //console.log('Ocurrio un error inesperado. Intenta nuevamente');
                    }
                }).always(function(){
                    //*document.getElementById("btn_consultarnotas").disabled = false;

                    $.unblockUI();
                });
            <? else: ?>
                switch(matricula){
                    case 1:
                        $.ajax({
                            type: 'POST',
                            url: <?= PUBLIC_PATH?> + 'management/registrarEstudiante/',
                            data: $('#frm_matriculaestudiante').serialize(),
                            dataType: 'json',
                            beforeSend: function(){
                                //document.getElementById("btn_consultarnotas").disabled = true;

                                $('body').addClass('menuopen');

                                $.blockUI({
                                    message: "Registrando y matriculando estudiante..."
                                });
                            },
                            success: function(data) {
                                $('body').removeClass('menuopen');
                                //document.getElementById("frm_codigoestudiante").reset();

                                if(data !== null && data.res === 'ok'){
                                    window.localStorage.idPagoMatricula = data.id;

                                    document.location = <?= PUBLIC_PATH?> + 'management/pagomatricula/' + data.id;

                                    console.log(data.res);
                                }else{
                                    console.log(data.msg);
                                }
                            },
                            error: function(){
                                //console.log('Ocurrio un error inesperado. Intenta nuevamente');
                            }
                        }).always(function(){
                            //*document.getElementById("btn_consultarnotas").disabled = false;

                            $.unblockUI();
                        });

                        break;
                    case 2:
                        $.ajax({
                            type: 'POST',
                            url: <?= PUBLIC_PATH?> + 'management/registrarMatricula/',
                            data: $('#frm_matriculaestudiante').serialize(),
                            dataType: 'json',
                            beforeSend: function(){
                                //document.getElementById("btn_consultarnotas").disabled = true;

                                $('body').addClass('menuopen');

                                $.blockUI({
                                    message: "Matriculando estudiante..."
                                });
                            },
                            success: function(data) {
                                $('body').removeClass('menuopen');
                                //document.getElementById("frm_codigoestudiante").reset();

                                if(data !== null && data.res === 'ok'){
                                    window.localStorage.idPagoMatricula = data.id;

                                    document.location = <?= PUBLIC_PATH?> + 'management/pagomatricula/' + data.id;

                                    console.log(data.res);
                                }else{
                                    console.log(data.msg);
                                }
                            },
                            error: function(){
                                //console.log('Ocurrio un error inesperado. Intenta nuevamente');
                            }
                        }).always(function(){
                            //document.getElementById("btn_consultarnotas").disabled = false;

                            $.unblockUI();
                        });

                        break;
                }
            <? endif; ?>
        }else{
            //validarcampos(documento, convertiranumero(region), convertiranumero(localidad), nombre, apellido, fechaNacimiento, convertiranumero(regionNacimiento), convertiranumero(localidadNacimiento), direccion, telefono, correoElectronico, nombreAcudiente, apellidoAcudiente, telefonoAcudiente, empresa, cargo, direccionEmpresa, telefonoEmpresa, convertiranumero(programa), codigoEstudiante, numeroMatricula, fechaMatricula);
            validarcampos(documento, convertiranumero(region), convertiranumero(localidad), nombre, apellido, fechaNacimiento, convertiranumero(regionNacimiento), convertiranumero(localidadNacimiento), direccion, telefono, correoElectronico, convertiranumero(programa), codigoEstudiante, numeroMatricula, fechaMatricula, valorMatricula);
        }
    });
    
    //nombreAcudiente, apellidoAcudiente, telefonoAcudiente, empresa, cargo, direccionEmpresa, telefonoEmpresa
    function validarcampos(documento, region, localidad, nombre, apellido, fechaNacimiento, regionNacimiento, localidadNacimiento, direccion, telefono, correoElectronico, programa, codigoEstudiante, numeroMatricula, fechaMatricula, valorMatricula){
        $inputfocus = null;
        $input = $('#txt_numerodocumento');
        if(documento.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#slt_regionE');
        if(region === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#slt_localidadE');
        if(localidad === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_nombre');
        if(nombre.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_apellido');
        if(apellido.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_fechanacimiento');
        if(fechaNacimiento.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#slt_regionN');
        if(regionNacimiento === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#slt_localidadN');
        if(localidadNacimiento === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_direccion');
        if(direccion.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_telefono');
        if(telefono.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_correoelectronico');
        if(correoElectronico.length === 0 || !validar_email(correoElectronico)){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        /*$input = $('#txt_nombreA');
        if(nombreAcudiente.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_apellidoA');
        if(apellidoAcudiente.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_telefonoA');
        if(telefonoAcudiente.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }*/
        /*$input = $('#txt_empresa');
        if(empresa.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_cargo');
        if(cargo.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_direccionE');
        if(direccionEmpresa.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_telefonoE');
        if(telefonoEmpresa.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }*/
        $input = $('#slt_programa');
        if(programa === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_codigoestudiantil');
        if(codigoEstudiante.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_numeromatricula');
        if(numeroMatricula.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_fechamatricula');
        if(fechaMatricula.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }
        $input = $('#txt_valormatricula');
        if(valorMatricula.length === 0){
            $input.addClass('entrada_textonovalido');
            if($inputfocus === null)$inputfocus = $input;
        }else{
            $input.removeClass('entrada_textonovalido');
        }

        if($inputfocus !== null){
            $('html, body').animate({scrollTop: $inputfocus.position().top+'px'}, 1000);
            $inputfocus.focus();
        }
    }
    
    $("#txt_numerodocumento").on('keyup', function (){
        if($(this).val().length > 0){
            $(this).removeClass('entrada_textonovalido');
            $('#txt_codigoestudiantil').removeClass('entrada_textonovalido');
        }else{
            $(this).addClass('entrada_textonovalido');
            $('#txt_codigoestudiantil').addClass('entrada_textonovalido');
        }
    });
    
    //#txt_empresa, #txt_cargo, #txt_direccionE, #txt_telefonoE
    //#txt_nombreA, #txt_apellidoA, #txt_telefonoA
    $("#txt_nombre, #txt_apellido, #txt_fechanacimiento, #txt_direccion, #txt_telefono, #txt_correoelectronico, #num_numerocuotas, #txt_valormatricula").on('keyup', function (){
        if($(this).val().length > 0){
            $(this).removeClass('entrada_textonovalido');
        }else{
            $(this).addClass('entrada_textonovalido');
        }
    });
    
    $('#slt_regionE').change(function(event){
        if(convertiranumero($('#slt_regionE option:selected').val()) === 0){
            $(this).addClass('entrada_textonovalido');
            $('#slt_localidadE').addClass('entrada_textonovalido');
        }else{
            $(this).removeClass('entrada_textonovalido');
        }
    });
    
    $('#slt_localidadE').change(function(event){
        if(convertiranumero($('#slt_localidadE option:selected').val()) === 0){
            $(this).addClass('entrada_textonovalido');
        }else{
            $(this).removeClass('entrada_textonovalido');
        }
    });
    
    $('#slt_regionN').change(function(event){
        if(convertiranumero($('#slt_regionN option:selected').val()) === 0){
            $(this).addClass('entrada_textonovalido');
            $('#slt_localidadN').addClass('entrada_textonovalido');
        }else{
            $(this).removeClass('entrada_textonovalido');
        }
    });
    
    $('#slt_localidadN').change(function(event){
        if(convertiranumero($('#slt_localidadN option:selected').val()) === 0){
            $(this).addClass('entrada_textonovalido');
        }else{
            $(this).removeClass('entrada_textonovalido');
        }
    });
    
    $('#slt_programa').change(function(event){
        if(convertiranumero($('#slt_programa option:selected').val()) === 0){
            $(this).addClass('entrada_textonovalido');
            $('#txt_valormatricula').val('0');
        }else{
            var valor = $('#slt_programa option:selected').data('valor');
            
            $(this).removeClass('entrada_textonovalido');
            $('#txt_valormatricula').val(valor);
        }
    });
</script>