<div id="dv_consultarmatricula" class="contenedor_opcionegresados">Consultar Matricula</div>
<a class="contenedor_opcionegresados" href="<?= PUBLIC_PATH?>management/matricular/">Matricular Estudiante</a>

<script type="text/javascript">
    if(!isNaN(window.localStorage.idPagoMatricula)){
        window.localStorage.removeItem('idPagoMatricula');
        window.localStorage.removeItem('idPagoValidacion');
    }
    
    $('#dv_consultarmatricula').on('click', function (){
        $.ajax({
            type: 'POST',
            url: <?= PUBLIC_PATH?> + 'management/consultamatricula/',
            data: {},
            beforeSend: function(){
                //document.getElementById("btn_consultarnotas").disabled = true;
                
                /*$('body').addClass('menuopen');
                
                $.blockUI({
                    message: "Procesando solicitud..."
                });*/
            },
            success: function(data) {
                //$('body').removeClass('menuopen');
                //document.getElementById("frm_codigoestudiante").reset();
                
                $('#sec_contenidologinadmin').html('');
                $('#sec_contenidologinadmin').html(data);
            },
            error: function(){
                //console.log('Ocurrio un error inesperado. Intenta nuevamente');
            }
        }).always(function(){
            //*document.getElementById("btn_consultarnotas").disabled = false;
            
            //$.unblockUI();
        });
    });
</script>