<div class="contenedor_formularioadmin contenedor_formulariomatricula">
    <span class="etiqueta_encabezadoformlarioadmin">MATRICULAR ESTUDIANTE</span>
    <div id="dv_semestrematricula">
        <div>
            <input id="rb_semestreuno" type="radio" name="matricula" value="1" checked>
            <span class="etiqueta_textoradioformularioadmin">Primer Semestre</span>
            <input id="rb_semestredostres" type="radio" name="matricula" value="2">
            <span class="etiqueta_textoradioformularioadmin">Segundo y Tercer Semetre</span>
        </div>
    </div>
    <div id="dv_buscardocumento" class="displaynone">
        <div>
            <span>Número de Documento</span>
            <input id="txt_numerodocumentoconsultar" class="entrada_datoformularioadmin" type="text" required="required" onkeypress="return soloNumeros(event);">
        </div>
        <div>
            <input id="btn_consultardocumento" class="boton_buscardocumento" type="button" value="Cargar Datos">
        </div>
    </div>
    <div id="dv_formulariomatricula"></div>
    
    <? //View::partial('management/formulariomatricula', false, array('tipodocumentos'=>$tipodocumentos, 'programas'=>$programas, 'semestres'=>$semestres, 'formapagos'=>$formapagos, 'paises'=>$paises, 'regiones'=>$regiones)); ?>
</div>

<script type="text/javascript">
    function cargarForm(bandera, documento){
        $.ajax({
            type: 'POST',
            url: <?= PUBLIC_PATH?> + 'management/formulariomatricula/',
            data: {
                tipoForm: bandera,
                documento: documento
            },
            beforeSend: function(){
                //document.getElementById("btn_consultarnotas").disabled = true;
                
                $('body').addClass('menuopen');
                
                $.blockUI({
                    message: "Cargando formulario de matricula..."
                });
            },
            success: function(data) {
                $('body').removeClass('menuopen');
                //document.getElementById("frm_codigoestudiante").reset();
                
                $('#dv_formulariomatricula').html('');
                $('#dv_formulariomatricula').html(data);
                
                rs();
            },
            error: function(){
                //console.log('Ocurrio un error inesperado. Intenta nuevamente');
            }
        }).always(function(){
            //document.getElementById("btn_consultarnotas").disabled = false;
            
            $.unblockUI();
        });
    }
    
    cargarForm(0, 0);
    
    $('#rb_semestreuno').on('click', function (){
        $('#dv_buscardocumento').addClass('displaynone');
        $('#txt_numerodocumentoconsultar').val('');
        $('#txt_numerodocumentoconsultar').removeClass('entrada_textonovalido');
        
        cargarForm(0, 0);
    });
    
    $('#rb_semestredostres').on('click', function (){
        //cargarForm(1);
        
        $('#dv_formulariomatricula').html('');
        $('#dv_buscardocumento').removeClass('displaynone');
        $('#txt_numerodocumentoconsultar').focus();
        
        rs();
    });
    
    $('#btn_consultardocumento').on('click', function (){
        var documento = $('#txt_numerodocumentoconsultar').val();
        
        if(documento.length > 0){
            $.ajax({
                type: 'POST',
                url: <?= PUBLIC_PATH?> + 'management/consultarDocumentoEstudiante/',
                data: {
                    documento: documento
                },
                dataType: 'json',
                beforeSend: function(){
                    //document.getElementById("btn_consultarnotas").disabled = true;
                    
                    /*$('body').addClass('menuopen');
                    
                    $.blockUI({
                        message: "Validando datos..."
                    });*/
                },
                success: function(data) {
                    //$('body').removeClass('menuopen');
                    //document.getElementById("frm_codigoestudiante").reset();
                    
                    $('#dv_formulariomatricula').html('');
                    $('#dv_formulariomatricula').html(data);
                    
                    if(data !== null && data.res === 'ok'){
                        /*window.location = "<?= PUBLIC_PATH?>management/administracion/";*/
                        
                        $('#dv_buscardocumento').addClass('displaynone');
                        $('#txt_numerodocumentoconsultar').val('');
                        
                        cargarForm(1, documento);
                    }else{
                        console.log(data.msg);
                    }
                },
                error: function(){
                    console.log('Ocurrio un error inesperado. Intenta nuevamente');
                }
            }).always(function(){
                //document.getElementById("btn_consultarnotas").disabled = false;
                
                //$.unblockUI();
            });
        }else{
            $input = $('#txt_numerodocumentoconsultar');
            if(documento.length === 0){
                $input.addClass('entrada_textonovalido');
                $input.focus();
            }else{
                $input.removeClass('entrada_textonovalido');
            }
        }
    });
    
    $('#txt_numerodocumentoconsultar').on('keyup', function() {
        var txt = $(this).val();
        
        if (txt.length <= 0) {
            $(this).addClass('entrada_textonovalido');
        } else {
            $(this).removeClass('entrada_textonovalido');
        }
    });
</script>