<a class="contenedor_opcionegresados" href="<?= PUBLIC_PATH?>management/matricular/">Matricular Estudiante</a>
<div id="dv_consultarmatricula" class="contenedor_opcionegresados">Consultar Matricula</div>

<script type="text/javascript">
    if(!isNaN(window.localStorage.idPagoMatricula)){
        window.localStorage.removeItem('idPagoMatricula');
        window.localStorage.removeItem('idPagoValidacion');
    }
    
    $('#dv_consultarmatricula').on('click', function (){
        $.ajax({
            type: 'POST',
            url: <?= PUBLIC_PATH?> + 'management/consultamatricula/',
            data: {},
            beforeSend: function(){
                
            },
            success: function(data) {
                $('#sec_contenidologinadmin').html('');
                $('#sec_contenidologinadmin').html(data);
            },
            error: function(){
                
            }
        }).always(function(){
            
        });
    });
</script>