<div class="contenedor_formularioadmin contenedor_formulariomatricula">
    <span class="etiqueta_encabezadoformlarioadmin">MATRICULAR ESTUDIANTE</span>
    <div id="dv_formulariomatricula"></div>
</div>

<script type="text/javascript">
    $.ajax({
            type: 'POST',
            url: <?= PUBLIC_PATH?> + 'management/formulariomatricula/',
            data: {
                tipoForm: 2,
                documento: 0
            },
            beforeSend: function(){
                $('body').addClass('menuopen');
                
                $.blockUI({
                    message: "Cargando formulario de matricula..."
                });
            },
            success: function(data) {
                $('body').removeClass('menuopen');
                
                $('#dv_formulariomatricula').html('');
                $('#dv_formulariomatricula').html(data);
                
                rs();
            },
            error: function(){
                
            }
        }).always(function(){
            $.unblockUI();
        });
</script>