<div id="dv_pagomatricula" class="contenedor_formularioadmin contenedor_formulariomatricula">
    <span class="etiqueta_encabezadoformlarioadmin">PAGO DE MATRICULA</span>
    <div class="contendor_pagomatricula">
        <? if($idAlumno===0): ?>
            <form id="frm_consultadocumentopagomatricula">
                <div>
                    <label>Número de Documento</label>
                    <input id="txt_documentopagomatricula" class="entrada_datoformularioadmin" name="documentopagomatricula" type="text" autofocus required="required" onkeypress="return soloNumeros(event);">
                </div><br>
                <div>
                    <input id="btn_consultardocumentopm" class="boton_buscardocumento" type="button" value="Consultar">
                </div>
            </form>
        <? else: ?>
            <div class="contenedor_datospagomatricula">
                <? switch($tipoPago):
                    case 1: ?>
                        <label><?= $nombre?></label>
                        <label><?= $abreviaturaid . ' ' . number_format($id, 0, '', '.')?></label>
                        <label>Programa: <?= $programa?></label>
                        <label>Sede: <?= ($sede==1)?'Pasto':'Ipiales';?></label>
                        <label>Número de Matricula: <?= $numeroMatricula?></label>
                        <label>Matricula realizada el <?= $fechaMatricula?></label>
                        <label>Tipo de Pago: CONTADO</label>
                        <label>Valor a Pagar: <?= number_format($valorsemestre, 0, '', '.')?></label>
                        
                        <? break;
                    case 2: ?>
                        <label><?= $nombre?></label>
                        <label><?= $abreviaturaid . ' ' . number_format($id, 0, '', '.')?></label>
                        <label>Programa: <?= $programa?></label>
                        <label>Sede: <?= ($sede==1)?'Pasto':'Ipiales';?></label>
                        <label>Número de Matricula: <?= $numeroMatricula?></label>
                        <label>Matricula realizada el <?= $fechaMatricula?></label>
                        <label>Tipo de Pago: A CUOTAS</label>
                        <label>Total a Pagar: <?= number_format($valorsemestre, 0, '', '.')?></label>
                        <label>Número de Cuotas: <?= $numeroCuotas?></label>
                        <div id="dv_cuotaspagomatricula">
                            <? for($i = 0; $i < $numeroCuotas; $i++): ?>
                                <div class="contendor_cuotapagomatricula">
                                    <label class="etiqueta_textocuota">Valor Cuota No. <?= $i + 1?>: <?= number_format($valorsemestre/$numeroCuotas, 0, '',  '.')?></label>
                                    
                                    <? if($i<$cuotasPagadas): ?>
                                        <label class="etiqueta_cuotapagada">Cuota Pagada</label>
                                        <a class="enlace_generarrecibopago" href="<?= PUBLIC_PATH?>pdf/recibopago/" target="_blanck">Generar Recibo</a>
                                    <? elseif($i==$cuotasPagadas): ?>
                                        <input class="boton_registrarPagoCuotaMatricula boton_pagarcuota" data-valor="<?= ($valorsemestre/$numeroCuotas)?>" type="button" value="Pagar Cuota">
                                    <? elseif($i>$cuotasPagadas): ?>
                                        <input class="boton_pagarcuotadisabled" type="button" value="Pagar Cuota" disabled="disabled">
                                    <? endif; ?>
                                </div>
                            <? endfor; ?>
                        </div>
                        
                        <? break;
                    default:
                        
                        break;
                endswitch; ?>
            </div>
            <? if($valorsemestre > 0): ?>
                <? if(!$estadosaldo): ?>
                    <div id="dv_saldopagomatricula">
                        <label id="lbl_saldopagomatricula">Saldo:&nbsp;<?= number_format(($valorsemestre - (($valorsemestre/$numeroCuotas) * $cuotasPagadas)), 0, '', '.')?></label>
                    </div>
                <? endif; ?>
            <? else: ?>
                <div id="dv_saldopagomatricula">
                    <label class="etiqueta_becamatricula">Estudiante Becado</label>
                    <label class="etiqueta_becamatricula">Valor Semestre Programa:&nbsp;<?= number_format($valorsemestreprograma, 0, '', '.')?></label>
                </div>
            <? endif; ?>
            <div id="dv_accionespagomatricula">
                <? if($valorsemestre > 0):
                    if($estadosaldo): ?>
                        <label class="etiqueta_matriculapagada">Total del valor de matricula pagado</label>
                        <div class="contenedor_recibopago">
                            <a class="enlace_generarrecibopago" href="<?= PUBLIC_PATH?>pdf/recibopago/" target="_blanck">Generar Recibo</a>
                        </div>
                    <? else: ?>
                        <? if($tipoPago == 1): ?>
                            <input id="btn_registrarpagocontadomatricula" class="boton_accionpagomatricula" type="button" value="Registrar Pago">
                        <? endif; ?>
                        <input id="btn_cancelarpagomatricula" class="boton_accionpagomatricula" type="button" value="Cancelar Pago">
                    <? endif;
                else: ?>
                    <input id="btn_registrarpagobeca" class="boton_accionpagomatricula boton_accionpagobeca" type="button" value="Registrar Pago Beca">
                    <input id="btn_cancelarpagomatricula" class="boton_accionpagomatricula" type="button" value="Cancelar Pago">
                <? endif; ?>
            </div>
        <? endif; ?>
    </div>
</div>
<div class="contendor_regresarprincipal">
    <a href="<?= PUBLIC_PATH?>management/pagos" class="etiqueta_regresarprincipal">Regresar</a>
</div>
<div id="dv_dialogodocumentoalumnoinexistente">
    <? Flash::info("El número de documento no se encuentra registrado en nuestra base de datos de estudiantes") ?>
</div>

<script type="text/javascript">
    $('#dv_dialogodocumentoalumnoinexistente').dialog({
        autoOpen: false,
        modal: true,
        resizable: false,
        closeOnEscape: false,
        buttons: {
            "Aceptar": function() {
                $('#dv_dialogodocumentoalumnoinexistente').dialog('close');
            }
        },
        close: function (){}
    });
    
    $('#btn_consultardocumentopm').on('click', function (){
        var identificacion = $('#txt_documentopagomatricula').val();
        
        if(identificacion.length > 0){
            $.ajax({
                type: 'POST',
                url: <?= PUBLIC_PATH?> + 'management/consultardocumentopagomatricula/',
                data: $('#frm_consultadocumentopagomatricula').serialize(),
                dataType: 'json',
                beforeSend: function(){
                    $('body').addClass('menuopen');

                    $.blockUI({
                        message: "Procesando solicitud..."
                    });
                },
                success: function(data) {
                    $('body').removeClass('menuopen');

                    if(data !== null && data.res === 'ok'){
                        window.localStorage.idPagoMatricula = identificacion;

                        document.location = <?= PUBLIC_PATH?> + 'management/pagomatricula/' + identificacion;
                    }else{
                        document.getElementById("frm_consultadocumentopagomatricula").reset();
                        $('#txt_documentopagomatricula').focus();

                        $('#dv_dialogodocumentoalumnoinexistente').dialog('open');

                        console.log(data.msg);
                    }
                },
                error: function(){
                    console.log('Ocurrio un error inesperado. Intenta nuevamente');
                }
            }).always(function(){
                $.unblockUI();
            });
        }else{
            $inputfocus = null;
            $input = $('#txt_documentopagomatricula');
            if(identificacion.length === 0){
                $input.addClass('entrada_textonovalido');
                if($inputfocus === null)$inputfocus = $input;
            }else{
                $input.removeClass('entrada_textonovalido');
            }
            
            if($inputfocus !== null){
                $('html, body').animate({scrollTop: $inputfocus.position().top+'px'}, 1000);
                $inputfocus.focus();
            }
        }
    });
    
    $('#txt_documentopagomatricula').keypress(function(e) {
        if(e.which == 13) {
            $(this).blur();
            $('#btn_consultardocumentopm').click();
        }
    });
    
    $('#txt_documentopagomatricula').on('keyup', function() {
        var txt = $(this).val();
        
        if (txt.length <= 0) {
            $(this).addClass('entrada_textonovalido');
        } else {
            $(this).removeClass('entrada_textonovalido');
        }
    });
    
    $('#btn_cancelarpagomatricula').on('click', function (){
        window.localStorage.removeItem('idPagoMatricula');
        
        document.location = <?= PUBLIC_PATH?> + 'management/pagomatricula/';
    });
    
    $('#btn_registrarpagocontadomatricula').on('click', function (){
        var valormatricula = <?= $valorsemestre?>,
            idmatricula = <?= $idMatricula?>;
        
        $.ajax({
            type: 'POST',
            url: <?= PUBLIC_PATH?> + 'management/registrarpagocontado/',
            data: {
                valor: valormatricula,
                idMatricula: idmatricula
            },
            dataType: 'json',
            beforeSend: function(){
                $('body').addClass('menuopen');

                $.blockUI({
                    message: "Registrando pago..."
                });
            },
            success: function(data) {
                $('body').removeClass('menuopen');

                if(data !== null && data.res === 'ok'){
                    document.location = <?= PUBLIC_PATH?> + 'management/pagomatricula/' + window.localStorage.idPagoMatricula;
                }else{
                    console.log(data.msg);
                }
            },
            error: function(){
                console.log('Ocurrio un error inesperado. Intenta nuevamente');
            }
        }).always(function(){
            $.unblockUI();
        });
    });
    
    $('#btn_registrarpagobeca').on('click', function (){
        var valormatricula = <?= $valorsemestreprograma?>,
            idmatricula = <?= $idMatricula?>;
        
        $.ajax({
            type: 'POST',
            url: <?= PUBLIC_PATH?> + 'management/registrarpagobeca/',
            data: {
                valor: valormatricula,
                idMatricula: idmatricula
            },
            dataType: 'json',
            beforeSend: function(){
                $('body').addClass('menuopen');

                $.blockUI({
                    message: "Registrando pago..."
                });
            },
            success: function(data) {
                $('body').removeClass('menuopen');

                if(data !== null && data.res === 'ok'){
                    document.location = <?= PUBLIC_PATH?> + 'management/pagomatricula/' + window.localStorage.idPagoMatricula;
                }else{
                    console.log(data.msg);
                }
            },
            error: function(){
                console.log('Ocurrio un error inesperado. Intenta nuevamente');
            }
        }).always(function(){
            $.unblockUI();
        });
    });
    
    $('.boton_registrarPagoCuotaMatricula').on('click', function (){
        var valormatricula = $(this).data('valor'),
            idmatricula = <?= $idMatricula?>;
        
        $.ajax({
            type: 'POST',
            url: <?= PUBLIC_PATH?> + 'management/registrarpagocuota/',
            data: {
                valor: valormatricula,
                idMatricula: idmatricula
            },
            dataType: 'json',
            beforeSend: function(){
                $('body').addClass('menuopen');
                
                $.blockUI({
                    message: "Registrando pago..."
                });
            },
            success: function(data) {
                $('body').removeClass('menuopen');
                
                if(data !== null && data.res === 'ok'){
                    document.location = <?= PUBLIC_PATH?> + 'management/pagomatricula/' + window.localStorage.idPagoMatricula;
                }else{
                    console.log(data.msg);
                }
            },
            error: function(){
                console.log('Ocurrio un error inesperado. Intenta nuevamente');
            }
        }).always(function(){
            $.unblockUI();
        });
    });
</script>