<?//= json_encode($programas)?>

<div id="dv_resultadoseguimientoegresados">
    <span id="sp_tituloresultadoseguimientoegresados">Seguimiento a Egresados</span>
    <div id="dv_opcionesresultadoseguimientoegresados">
        <div>
            <span>Programa</span>
            <select id="slt_programasegresados">
                <option value="0">Seleccionar Programa</option>
                <? foreach($programas as $programa): ?>
                    <option value="<?= $programa->id_programa?>"><?= $programa->nombre_programa?></option>
                <? endforeach; ?>
            </select>
        </div>
        <div>
            <span>Año Egreso</span>
            <select id="slt_aniosegresados">
                <option value="0">Seleccionar Año</option>
            </select>
        </div>
        <div>
            <span>Periodo</span>
            <select id="slt_periodoegresados">
                <option value="0">Seleccionar Periodo Académico</option>
            </select>
        </div>
    </div>
    <div id="dv_resultadoegresados" class="contenedor_resultadoegresados displaynone"></div>
</div>

<script type="text/javascript">
    $('#slt_programasegresados').change(function() {
        if($(this).val().length > 0){
            var programa = $(this).val();
            
            $.ajax({
                type: 'POST',
                url: "<?= PUBLIC_PATH?>management/cargaraniosegresadosprograma/",
                data: {
                    programa: programa
                },
                dataType: 'json',
                beforeSend: function(){
                    //document.getElementById("btn_consultarnotas").disabled = true;
                    
                    $('body').addClass('menuopen');
                    
                    $.blockUI({
                        message: "Cargando datos..."
                    });
                },
                success: function(data){
                    $('body').removeClass('menuopen');
                    //document.getElementById("frm_codigoestudiante").reset();
                    
                    $('#dv_resultadoegresados').html('').addClass('displaynone');
                    $('#slt_periodoegresados').empty();
                    $('#slt_periodoegresados').append('<option value="0">Seleccionar Periodo Académico</option>');
                    $('#slt_aniosegresados').empty();
                    $('#slt_aniosegresados').append('<option value="0">Seleccionar Año</option>');
                    $('#slt_aniosegresados').append('<option value="1">Todos</option>');
                    
                    for(var i = 0; i < data.length; i++){
                        $('#slt_aniosegresados').append('<option value="' + data[i].anio + '">' + data[i].anio + '</option>');
                    }
                },
                error: function (xhr, ajaxOptions, thrownError){ }
            }).always(function(){
                //document.getElementById("btn_consultarnotas").disabled = false;
                
                $.unblockUI();
            });
        }
    });
    
    $('#slt_aniosegresados').change(function() {
        if($(this).val() > 0){
            $('#dv_resultadoegresados').html('').addClass('displaynone');
            $('#slt_periodoegresados').empty();
            $('#slt_periodoegresados').append('<option value="0">Seleccionar Periodo Académico</option>');
            $('#slt_periodoegresados').append('<option value="1">Periodo A</option>');
            $('#slt_periodoegresados').append('<option value="2">Periodo B</option>');
        }else{
            $('#dv_resultadoegresados').html('').addClass('displaynone');
            $('#slt_periodoegresados').empty();
            $('#slt_periodoegresados').append('<option value="0">Seleccionar Periodo Académico</option>');
        }
    });
    
    $('#slt_periodoegresados').change(function() {
        if($(this).val().length > 0){
            var programa = $('#slt_programasegresados').val(),
                anio = $('#slt_aniosegresados').val(),
                periodo = $(this).val();
            
            $.ajax({
                type: 'POST',
                url: "<?= PUBLIC_PATH?>management/cargaregresados/",
                data: {
                    programa: programa,
                    anio: anio,
                    periodo: periodo
                },
                beforeSend: function(){
                    //document.getElementById("btn_consultarnotas").disabled = true;
                    
                    $('body').addClass('menuopen');
                    
                    $.blockUI({
                        message: "Cargando datos..."
                    });
                },
                success: function(data){
                    $('body').removeClass('menuopen');
                    //document.getElementById("frm_codigoestudiante").reset();
                    
                    $('#dv_resultadoegresados').html('');
                    $('#dv_resultadoegresados').html(data);
                    $('#dv_resultadoegresados').removeClass('displaynone');
                },
                error: function (xhr, ajaxOptions, thrownError){ }
            }).always(function(){
                //document.getElementById("btn_consultarnotas").disabled = false;
                
                $.unblockUI();
            });
        }
    });
</script>