<?php
/**
 * KumbiaPHP web & app Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://wiki.kumbiaphp.com/Licencia
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@kumbiaphp.com so we can send you a copy immediately.
 *
 * Paginador "classic" para aplicaciones
 *
 * Parametros del paginador:
 *   page: objeto obtenido al invocar al paginador
 *   show: numero de paginas que se mostraran en el paginador
 *   url: url para la accion que efectua la paginacion, por defecto "module/controller/page/"
 *        y se envia por parametro el numero de pagina
 *
 * @category   Kumbia
 * @package    Partials
 * @copyright  Copyright (c) 2005-2015 Kumbia Team (http://www.kumbiaphp.com)
 * @license    http://wiki.kumbiaphp.com/Licencia     New BSD License
 */

if(!isset($url)) {
    extract(Router::get());
    $url = "$controller/page";
    if($module) {
        $url = "$module/$url";
    }
}

if(!isset($show)) {
    $show = 10;
}

$half = floor($show/2);

// Calculando el inicio de paginador centrado
if ($page->current <= $half) {
    $start = 1;
} elseif (($page->total - $page->current)<$half) {
    $start = $page->total - $show + 1;
    if($start < 1) $start = 1;
} else {
    $start = $page->current - $half;
}
?>

<div class="paginator">
    <? /*if($page->prev==1) echo Html::link("$url/", 'Anterior', 'title="Ir a la pág. anterior" class="nextprev" rel="prev"'); // Se coloca el enlace sin número de página para la pagina 1
        elseif($page->prev) echo Html::link("$url/$page->prev/", 'Anterior', 'title="Ir a la pág. anterior" class="nextprev" rel="prev"') */?>
    <? if($page->prev): ?>
        <span class="etiqueta_direccionpaginacion" onclick="cargaregresados(<?= $page->prev?>, <?= $programa?>, <?= $anio?>);"><</span>
    <? endif; ?>
    
    <? if($start == 1): //se coloca el link sin número de página para la página 1
        $start = 2;
        $show -= 1;
        
        if($page->current == 1): ?>
            <span class="etiqueta_opcionpaginacion">1</span>
        <? else: ?>
            <span class="etiqueta_opcionpaginacion" onclick="cargaregresados(1, <?= $programa?>, <?= $anio?>);">1</span>
        <? endif;
    endif; ?>

    <? for($i=$start; $i<=$page->total && $i<($start + $show); $i++): ?>
        <? /*echo $i==$page->current ? "<strong>$i</strong>" : Html::link("$url/$i/", $i)*/ ?>
        <? if($i == $page->current): ?>
            <span class="etiqueta_opcionpaginacion"><?= $i?></span>
        <? else: ?>
            <span class="etiqueta_opcionpaginacion" onclick="cargaregresados(<?= $i?>, <?= $programa?>, <?= $anio?>);"><?= $i?></span>
        <? endif;
    endfor; ?>

    <? //if($page->next) echo Html::link("$url/$page->next/", 'Siguiente', 'title="Ir a la pág. siguiente" class="nextprev" rel="next"') ?>
    <?if($page->next):?>
        <span class="etiqueta_direccionpaginacion" onclick="cargaregresados(<?= $page->next?>, <?= $programa?>, <?= $anio?>);">></span>
    <?endif;?>
</div>
